Enable GDB and AFMI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,7 +49,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        amlg-postfix: ['-st', '-mt']
+        amlg-postfix: ['-st', '-mt-afmi']
 
     steps:
 
@@ -86,12 +86,38 @@ jobs:
       id: run
       timeout-minutes: 15
       run: |
+        # Install GDB
+        sudo apt-get install -y gdb
+        echo "GDB installation complete"
+
+        # Don't immediately fail if GDB exits with a non-zero code
+        set +e
+
         # Set stack size and run (stack size adjustments cannot be done with cmake on Linux)
+        ulimit -s 524288
         echo "Note: output is supressed due to length. See build artifacts for full logs."
         echo "Running..."
-        ulimit -s 524288
-        ./amalgam${{ matrix.amlg-postfix }} --debug-internal-memory tic_tac_toe_evolver.amlg -target-time 300 > logs.txt 2>&1 
-        echo "Done"
+
+        # Capture GDB output
+        gdb_output=$(gdb -batch -ex run -ex backtrace --args ./amalgam${{ matrix.amlg-postfix }} --debug-internal-memory tic_tac_toe_evolver.amlg -target-time 300 > logs.txt 2>&1)
+        gdb_exit_code=$?
+        echo "$gdb_output" >> logs.txt
+
+        # Evaluate GDB exit code and exit this workflow accordingly
+        if [[ $gdb_exit_code -ne 0 ]]; then
+          echo "$gdb_output" | tail -n 6
+          # If GDB exited with an error but the test process passed, exit 0
+          if echo "$gdb_output" | tail -n 6 | grep -q "exited normally"; then
+            exit 0
+          # Else, the test process failed, exit 1
+          else
+            exit 1
+          fi
+        else
+          # If GDB exited with code 0, there was a segfault
+          echo "$gdb_output"
+          exit 139
+        fi
 
     - name: Compress 'evolve' directory
       if: always()
